### ISSUE TITLE
armv7 seems very broken

### ISSUE THREAD

**Issue by selfisekai** [dart-musl/dart#5]
I've tried to bootstrap dart with [dart-musl 2.19.2](https://github.com/dart-musl/dart/releases/tag/2.19.2). x86_64 and aarch64 work great, but armv7 fails with fireworks: https://gitlab.alpinelinux.org/selfisekai/aports/-/jobs/1017797

**Comment by ntkme** [comment]
2.19.6 is supposed to be bootstrapped with 2.19.0-374.0.dev:

https://github.com/dart-lang/sdk/blob/2.19.6/DEPS#L50

Can you please try bootstrap with that version instead and see if the issue is still there?

If you need to get a build of 2.19.0-374.0.dev, let me know and I can manually trigger a build in this project.

**Comment by selfisekai** [comment]
can you trigger it? for some reason I don't have the workflow_dispatch available in my fork.

**Comment by ntkme** [comment]
https://github.com/dart-musl/dart/releases/tag/2.19.0-374.0.dev

**Comment by selfisekai** [comment]
did not get to it, 3.0.0 works correctly
